variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  JAVA_HOME: "/home/jonathan/.jdks/openjdk-22.0.1"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - lint
  - build
  - test
  - deploy

licensing:
  stage: lint
  before_script:
    - export PATH="$HOME/.local/bin:$PATH"
    - which reuse || echo "REUSE NOT FOUND"
    - reuse --version
  script:
    - reuse lint
  tags:
    - minecraft

# Build JAR files for each Minecraft & Fabric version
build_mod:
  stage: build
  before_script:
    - export PATH=$JAVA_HOME/bin:$PATH
    - java -version
  script:
    - ./build.sh
  artifacts:
    paths:
      - creaturechat-*.jar
      - fabric-api-*.jar
  tags:
    - minecraft

# Optional test (gpt 3.5)
gpt-3.5-turbo:
  stage: test
  script:
    - echo "Running tests with gpt-3.5-turbo"
    - ./gradlew test --info
  when: manual
  artifacts:
    paths:
      - build/reports/tests/test/*
  tags:
    - minecraft

# Optional test (gpt 4o)
gpt-4o:
  stage: test
  script:
    - echo "Running tests with gpt-4o"
    - export API_MODEL="gpt-4o"
    - ./gradlew test --info
  when: manual
  artifacts:
    paths:
      - build/reports/tests/test/*
  tags:
    - minecraft

# Optional test (llama3-8b)
llama3-8b:
  stage: test
  script:
    - echo "Running tests with llama3-8b"
    - export API_URL="http://127.0.0.1:4000/v1/chat/completions"
    - export API_MODEL="llama3"
    - ./gradlew test --info
  when: manual
  artifacts:
    paths:
      - build/reports/tests/test/*
  tags:
    - minecraft

# Deploy to Modrinth
Modrinth:
  stage: deploy
  when: manual
  script:
    - chmod +x ./deploy-modrinth.sh
    - ./deploy-modrinth.sh
  only:
    - develop
  artifacts:
    paths:
      - response.txt
  tags:
    - minecraft

# Deploy to CurseForge
CurseForge:
  stage: deploy
  when: manual
  script:
    - chmod +x ./deploy-curseforge.sh
    - ./deploy-curseforge.sh
  only:
    - develop
  artifacts:
    paths:
      - response.txt
  tags:
    - minecraft
