variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  JAVA_HOME: "/home/jonathan/.jdks/openjdk-22.0.1"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build

build_mod:
  stage: build
  before_script:
    - export PATH=$JAVA_HOME/bin:$PATH
    - java -version
  script:
    - |
      declare -a versions=("1.20")
      declare -a mappings=("1.20+build.1")
      declare -a fabric_versions=("0.83.0+1.20")

      for i in "${!versions[@]}"; do
        minecraft_version="${versions[$i]}"
        yarn_mappings="${mappings[$i]}"
        fabric_version="${fabric_versions[$i]}"

        echo "****"
        echo "Building for Minecraft Version $minecraft_version with Fabric $fabric_version\n"
        echo "****"

        # Replace versions before build attempt
        sed -i "s/minecraft_version=.*/minecraft_version=$minecraft_version/" gradle.properties
        sed -i "s/yarn_mappings=.*/yarn_mappings=$yarn_mappings/" gradle.properties
        sed -i "s/loader_version=.*/loader_version=0.15.11/" gradle.properties
        sed -i "s/fabric_version=.*/fabric_version=$fabric_version/" gradle.properties

        # Update minecraft version in fabric.mod.json
        sed -i "s/\"minecraft\": \".*\"/\"minecraft\": \">=$minecraft_version <${minecraft_version%.*}.$((${minecraft_version##*.}+1))\"/" src/main/resources/fabric.mod.json
        echo "Contents of fabric.mod.json:"
        cat src/main/resources/fabric.mod.json

        ./gradlew build
        find build/libs -type f -name '*sources*.jar' -exec rm {} \;
        mv build/libs/creaturechat-*.jar .

        FABRIC_API_JAR="fabric-api-${fabric_version}.jar"
        DOWNLOAD_URL="https://github.com/FabricMC/fabric/releases/download/${fabric_version//+/%2B}/${FABRIC_API_JAR}"
        wget -q -O "${FABRIC_API_JAR}" $DOWNLOAD_URL
        ls . -la
      done
  artifacts:
    paths:
      - creaturechat-*.jar
      - fabric-api-*.jar
  only:
    - improve-1.20-support
  tags:
    - minecraft
