variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build

build_mod:
  stage: build
  script:
    - ./gradlew build
    - find build/libs -type f -name '*sources*.jar' -exec rm {} \;
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - develop
  tags:
    - minecraft
